### ISSUE TITLE
Updates needed to work with Stack versions >= 2.1.1

### ISSUE THREAD

**Issue by malob** [AleXoundOS/haskell-stack-mirror-script#8]
It looks like Stack changed a bunch of stuff in version 2 that effects this project. So far they all seem to relate to the `config.yaml` file:

  * `package-indices` now requires `hackage-security` (see [here](https://docs.haskellstack.org/en/stable/yaml_configuration/#package-indices)). I think a workaround for this could be:
    ```yaml
    package-indices:
    - name: Hackage
       download-prefix: $MIRROR_URL/packages/
       http: $MIRROR_URL/01-index.tar.gz
       hackage-security:
         keyids: [""]
         key-threshold: 0        
    ```
  * `lts-build-plans` and `nightly-build-plans` are no longer supported. As far as I can tell, there's no alternative/workaround for this. It looks like one can workaround this on a per project basic though by specifying a snapshot location in `stack.yaml` (see [here](https://docs.haskellstack.org/en/stable/pantry/#snapshot-location)). So adding a note about that to the readme might be helpful.
